"use strict";

var WINDOWS_WITDH = 800;
var WINDOWS_HEIGHT = 600;

var PADDLE_WIDTH = 10;
var PADDLE_HEIGHT = 100;
var PADDLE_SPEED_PLAYER = 0.9;
var PADDLE_SPEED_COMPUTER = 0.5;
var PADDLE_GAP = 20;

var BALL_RADIUS = 8;
var BALL_SPEED = 0.15;

var WALL_SIZE = 10;
